### ISSUE TITLE
Main.py

### ISSUE THREAD

**Issue by urielkelman** [camicodina/TP-Grupal1-AlgoritmosIGuarna#8]
Correcciones sobre el main:

- Recuerden que pueden poner los imports  como:

from biblioteca import funcion

Esto les ahorra tener que hacer algo del estilo: biblioteca.funcion(), que les pasó con el "ca.cargar_archivo()". Ojo con el nombre ca, no indica qué es, es demasiado genérico. Lo mismo con los demás módulos. Utilizando la estructura para imports nombrada arriba, pueden empolijarlo.

**Comment by camicodina** [comment]
Corregido! Muchas gracias
